In [35]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_excel("C:\\Users\\HP\\Downloads\\Hotel Customer.xlsx")

In [3]:
data

     Rating     Category               Keyword
0         4  Personality       Inviting Warmth
1         4  Personality       Top Autenticity
2         4  Personality       Endearing Charm
3         4  Personality     Intuitive Insight
4         4  Personality     Driven to Deliver
..      ...          ...                   ...
192       1   Leadership   Short-Lived Efforts
193       1   Leadership     Unfair Tendencies
194       1   Leadership     Disengaging Vibes
195       1   Leadership     Judgmental Stance
196       1   Leadership  Uninfluential Impact

[197 rows x 3 columns]

In [4]:
data.head()

   Rating     Category            Keyword
0       4  Personality    Inviting Warmth
1       4  Personality    Top Autenticity
2       4  Personality    Endearing Charm
3       4  Personality  Intuitive Insight
4       4  Personality  Driven to Deliver

In [5]:
data.tail()

     Rating    Category               Keyword
192       1  Leadership   Short-Lived Efforts
193       1  Leadership     Unfair Tendencies
194       1  Leadership     Disengaging Vibes
195       1  Leadership     Judgmental Stance
196       1  Leadership  Uninfluential Impact

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 197 entries, 0 to 196
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Rating    197 non-null    int64
 1   Category  197 non-null    object
 2   Keyword   197 non-null    object
dtypes: int64(1), object(2)
memory usage: 4.7+ KB

In [7]:
data.describe()

           Rating
count  197.000000
mean     2.695431
std      1.181762
min      1.000000
25%      1.000000
50%      3.000000
75%      4.000000
max      4.000000

In [8]:
data.Category.unique()

array(['Personality', 'Professionalism', 'Communication', 'Knowledge',
       'Leadership'], dtype=object)

In [9]:
data.Keyword.unique()

array(['Inviting Warmth', 'Top Autenticity', 'Endearing Charm',
       'Intuitive Insight', 'Driven to Deliver', 'Flame of Passion',
       'Wildly Enthusiastic', 'People-Centric Mastery', 'Truly Genuine',
       'Magnetic Charisma', 'Heartfelt Care', 'Thoughtful Care',
       'Observant Star', 'Anticipating Needs', 'Confident Champion',
       'Welcoming Beacon', 'Relaxed Brilliance', 'Attentive Engagement',
       'Conscientious Pro', 'Accommodating Magician', 'Self-Assured Whiz',
       'Approachable Warmth', 'Diligent Commitment ', 'Formal Courtesy',
       'Helpful Joy', 'Polite Bliss', 'Empathetic Listener',
       'Courteous Questioning', 'Curious Listening', 'Reassuring Aura',
       'Polite Responses', 'Talkative Vibes', 'Respectful Interactions',
       'Expert Insigths', 'Savvy Pro', 'Insightful Expertise',
       'Specialised Expert', 'Profoundly Detailed', 'In-Depth Knowledge',
       'Enlightening Brilliance', 'Wisdom-Filled Mastery',
       'Inclusive Connector', 'Impartial Judge', 'Trustworthy Pillar',
       'Accountable Ally', 'Encouraging Guardian', 'Inspiring Muse',
       'Motivation Catalyst', 'Communicative Pro', 'Empowering Push',
       'Others Oriented', 'Enduring Optimist', 'Ethical Champ',
       'Pro Influencer', 'Supportive Cheer On', 'Transparent Soul',
       'Humble Spirit', 'Fairness Fanatic', 'Acceptance Ace',
       'Responsible Navigator', 'People Developer',
       'Spontaneous Brilliance', 'Relentless Persistence',
       'Compassionate Care', 'Respectful', 'Friendly', 'Pleasant',
       'Considerate', 'Willing', 'Spirited', 'Motivated', 'Patient',
       'Honest', 'Outgoing', 'Committed', 'Energetic', 'Decisive',
       'Efficient', 'Practical', 'Skilled', 'Resourceful', 'Flexible',
       'Organized', 'Planned', 'Consistent', 'Timely', 'Professional',
       'Effective', 'Competent', 'Dynamic', 'Adaptable', 'Proactive',
       'Structured', 'Fast', 'Meticulous', 'Productive', 'Talented',
       'Responsive', 'Expressive', 'Captivating', 'Engaging',
       'Entertaining', 'Convincing', 'Dimplomatic', 'Eloquent ',
       'Story-Teller', 'Understanding', 'Listener', 'Tactful',
       'Knowledgeable', 'Proficient', 'Well-Rounded', 'Up to Date',
       'Informed', 'Persuasive', 'Assertive', 'Problem-Solver',
       'Conflict-Solver', 'Delegate', 'Coach', 'Mentor', 'Negotiate',
       'Serious', 'Aloof', 'Measured', 'Hesitant', 'Passive', 'Apathetic',
       'Candid', 'Timid', 'Indifferent', 'Uninviting', 'Task-Oriented',
       'Unaware', 'Reactive', 'Cocky', 'Cold ', 'Nervous', 'Reserved',
       'Monotonous', 'Quiet', 'Distant', 'Passable', 'Conventional',
       'Impulsive', 'Uncaring Approach', 'Unfriendly Demanour',
       'Disrespectful Attitude', 'Lack of Consideration',
       'Dishonest Communication', 'Appears Uninterested',
       'Lack of Passion', 'Impatient Apperance', 'Disengaged Presence',
       'Inadequately Skilled', 'Inadequate Focus', 'Sluggishly paced',
       'Overbearing Attitude', 'Negligent Behavior', 'Casually Laid-Back',
       'Hasty Execution', 'Inflexibly Rigid', 'Chaotically Disorganized',
       'Error-Prone Actions', 'Careless Execution',
       'Ineffectively Operational', 'Neglegtful Execution',
       'Nonchalant Approach', 'Rushed Interaction',
       'Inappropriate Conduct', 'Unprofessional Conduct ',
       'Unmannerly Discourse', 'Rude Conduct', 'Tactless Expressions',
       'Lack of Listening ', 'Confusing Communication',
       'Limited Knowledge', 'Surface-Level Insights',
       'Uninformed Competence', 'Novice Awareness',
       'Exclusionary Approach', 'Bias Alert', 'Unreliable Actions',
       'Irresponsible Behavior', 'Discouraging Attitude',
       'Demotivating Presence', 'Micro Mania', 'Self-Oriented Focus',
       'Questionable Ethics', 'Unsatisfying Support',
       'Information Gate Keeper', 'Short-Lived Efforts',
       'Unfair Tendencies', 'Disengaging Vibes', 'Judgmental Stance',
       'Uninfluential Impact'], dtype=object)

In [10]:
data.Rating.value_counts()

Rating
4    65
3    58
1    51
2    23
Name: count, dtype: int64

In [11]:
data.Keyword.value_counts()

Keyword
Others Oriented         2
Measured                1
Passive                 1
Apathetic               1
Candid                  1
                       ..
Willing                 1
Spirited                1
Motivated               1
Patient                 1
Uninfluential Impact    1
Name: count, Length: 196, dtype: int64

In [12]:
data.Category.value_counts()

Category
Professionalism    59
Leadership         50
Personality        43
Communication      27
Knowledge          18
Name: count, dtype: int64

In [13]:
data.isnull()

     Rating  Category  Keyword
0     False     False    False
1     False     False    False
2     False     False    False
3     False     False    False
4     False     False    False
..      ...       ...      ...
192   False     False    False
193   False     False    False
194   False     False    False
195   False     False    False
196   False     False    False

[197 rows x 3 columns]

In [14]:
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier

C:\Users\HP\anaconda3\shreyansh data  science\lib\site-packages\scipy\__init__.py:138: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.4)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion} is required for this version of "

In [15]:
label_encoder = LabelEncoder()
data['Category'] = label_encoder.fit_transform(data['Category'])

In [16]:
X = data[['Rating', 'Category']]
y = data['Keyword']
y

0           Inviting Warmth
1           Top Autenticity
2           Endearing Charm
3         Intuitive Insight
4         Driven to Deliver
               ...
192     Short-Lived Efforts
193       Unfair Tendencies
194       Disengaging Vibes
195       Judgmental Stance
196    Uninfluential Impact
Name: Keyword, Length: 197, dtype: object

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train

     Rating  Category
5         4         3
65        3         3
137       2         4
97        3         4
169       1         4
..      ...       ...
106       3         0
14        4         4
92        3         4
179       1         1
102       3         0

[157 rows x 2 columns]

In [18]:
X_test

     Rating  Category
140       2         0
113       3         1
16        4         4
75        3         3
155       1         4
186       1         2
69        3         3
55        4         2
18        4         4
170       1         4
175       1         0
15        4         4
162       1         4
60        4         2
115       3         2
114       3         1
146       1         3
9         4         3
73        3         3
190       1         2
112       3         1
93        3         4
139       2         0
45        4         2
85        3         4
67        3         3
147       1         3
174       1         0
30        4         0
68        3         3
82        3         4
119       3         2
184       1         2
24        4         4
132       2         3
95        3         4
56        4         2
19        4         4
122       3         2
76        3         3

In [19]:
y_train

5           Flame of Passion
65                Respectful
137                    Cold
97                  Talented
169       Rushed Interaction
               ...
106             Story-Teller
14        Confident Champion
92                 Proactive
179    Uninformed Competence
102             Entertaining
Name: Keyword, Length: 157, dtype: object

In [20]:
y_test

140                Monotonous
113                Up to Date
16         Relaxed Brilliance
75                  Committed
155      Inadequately Skilled
186     Demotivating Presence
69                    Willing
55           Transparent Soul
18          Conscientious Pro
170     Inappropriate Conduct
175        Lack of Listening
15           Welcoming Beacon
162          Inflexibly Rigid
60      Responsible Navigator
115                Persuasive
114                  Informed
146         Uncaring Approach
9           Magnetic Charisma
73                     Honest
190      Unsatisfying Support
112              Well-Rounded
93                 Structured
139                  Reserved
45       Encouraging Guardian
85                 Consistent
67                   Pleasant
147       Unfriendly Demanour
174      Tactless Expressions
30           Polite Responses
68                Considerate
82                   Flexible
119                  Delegate
184    Irresponsible Behavior
24                Helpful Joy
132                Uninviting
95                 Meticulous
56            Others Oriented
19     Accommodating Magician
122                 Negotiate
76                  Energetic
Name: Keyword, dtype: object

In [21]:

clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)

DecisionTreeClassifier()

In [22]:
y_pred=clf.predict(X_test)
#y_pred

In [23]:
import random

# Define the keywords with their ratings and categories
keywords = [
    (4, 'Personality', [
        'Inviting Warmth', 'Top Authenticity', 'Endearing Charm', 'Intuitive Insight', 'Driven to Deliver',
        'Flame of Passion', 'Wildly Enthusiastic', 'People-Centric Mastery', 'Truly Genuine', 'Magnetic Charisma',
        'Heartfelt Care'
    ]),
    # ... (other categories with their keywords)
    (1, 'Leadership', [
        'Exclusionary Approach', 'Bias Alert', 'Unreliable Actions', 'Irresponsible Behavior', 'Discouraging Attitude',
        'Demotivating Presence', 'Micro Mania', 'Self-Oriented Focus', 'Questionable Ethics', 'Unsatisfying Support',
        'Information Gate Keeper'
    ]),
    
    (4, 'Professionalism', [
        'Thoughtful Care','Observant Star','Anticipating Needs','Confident Champion','Welcoming Beacon','Relaxed Brilliance',
        'Attentive Engagement','Conscientious Pro','Accommodating Magician','Self Assured Whiz','Approachable Warmth',
        'Deligent Commitment','Formal Courtesy','Helpful Joy','Polite Bliss'
    ]),
    
    (4, 'Communication', [
        'Empathetic Listener','Courteous Questioning','Curioud Listening','Reassuring Aura','Polite Responses','Talkative Vibes',
        'Respectful Interaction'
    ]),
    
    (4, 'Knowledge', [
        'Expert Insights','Savvy Pro','Insightful Expertise','Specialised Expert','Profoundly Detailed','In-Depth Knowledge',
        'Enlightening Brilliance','Wisdom-Filled Mastery'
    ]),
    
    (4, 'Leadership', [
        'Inclusive Connector','Impartial Judge','Trustworthy Pillar','Accountable Ally','Encouraging Gaurdian','Inspiring Muse',
        'Motivation Catalyst','Communicative Pro','Empowering Push','Others Oriented','Enduring Optimist','Ethical Champ','Pro Influencer',
        'Supportive Cheer On','Transparent Soul','Others Oriented','Humble Spirit','Fairness Fanatic','Acceptance Ace','Responsible Navigator',
        'People Developer','Spontaneous Brlliance','Relentless Persistence','Compassionate Care'
    ]),
    
    (3, 'Peronality', [
        'Respectful','Friendly','Pleasant','Considerate','Willing','Spirited','Motivated','Patient','Honest','Outgoing','Committed',
        'Energetic Decisive'
    ]),
    
    (3, 'Professionalism', [
        'Efficient','Practical','Skilled','Resourceful','Flexible','Organized','Planned','Consistent','Timely','Professional',
        'Effective','Competent','Dynamic','Adaptable','Proactive','Structured','Fast','Meticulous','Productive','Talented','Responsive'
    ]),
    
    (3, 'Communication',[
        'Expressive','Captivating','Engaging','Entertaining','Convincing','Dimplomatic','Eloquent','Story-Teller','Understanding',
        'Listener','Tactful'
    ]),
    
    (3, 'Leadership',[
        'Persuasive','Assertive','Problem-Solver','Conflict-Solver','Delegate','Coach','Mentor','Negotiate'
    ]),
    
    (3, 'Knowledge',[
        'Knowledgeable','Proficient','Well-Rounded','Up to Date','Informed'
    ]),
    
    (2, 'Personality',[
        'Serious','Aloof','Measured','Hesitent','Passive','Apathetic','Candid','Timid','Indifferent','Uninviting'
    ]),
    
    (2, 'Profesionalism' ,[
        'Task-Oriented','Unaware','Reactive','Cocky','Cold','Nervous'
    ]),
    
    (2, 'Communication' ,[
         'Reserved','Monotonous','Quiet','Distant'
    ]),
    
    (2, 'Knowledge' ,[
        'Passable'
    ]),
    
    (2, 'Leadership' ,[
        'Conventional','Impulsive'
    ]),
    
    (1, 'Personality' ,[
        'Uncaring Approach','Unfriendly Demanour','Disrespectful Attitude','Lack of Consideration','Dishonest Communication','Appears Uninterested',
        'Lack of Passion','Impatient Apperance','Disengaged Presence'
    ]),
    
    (1, 'Professionalism' ,[
        'Inadequate Skilled','Inadequate Focus','Sluggishly paced','Overbearing Attitude','Negligent Behavior','Casually Laid-Back',
        'Hasty Execution','Inflexibly Rigid','Chaotically Disorganized','Error-Prone Actions','Careless Execution','Ineffectively Operational',
        'Neglegtful Execution','Nonchalant Approach','Rushed Interaction','Inappropriate Conduct','Unprofessional Conduct'
    ]),
    
    (1, 'Communication' ,[
        'Unmannerly Discourse','Rude Conduct','Tactless Expressions','Lack of Listening','Confusing Communication'
    ]),
    
    (1, 'Knowledge' ,[
        'Limited Knowledge','Surface-Level Insights','Uninformed Impetence','Novice Awareness'
    ]),
    
    (1, 'Leadership' ,[
        'Exclusionary Approach','Bias Alert','Unreliable Actions','Irresponsible Behaviour','Discouraging Attitude','Demotivating Presence','Micro Mania',
        'Self-Oriented Focus','Questionable Ethics','Unsatisfying Support','Information Gate Keeper','Short Lived Efforts','Unfair Tendencies',
        'Disengaging Vibes','Judgmental Stance','Uninfluential Impact'
    ])   
]

In [24]:
def generate_keywords_by_rating(rating, num_keywords):
    selected_keywords = []
    selected_Ratings = []
    selected_categories = []
    for keyword_rating, _, keyword_list in keywords:
        if keyword_rating == rating:
            selected_keywords.extend(keyword_list)
    return random.sample(selected_keywords, num_keywords)

In [25]:
num_keywords_to_generate = 10
selected_rating = int(input("Enter the desired rating (1-4): "))
selected_keyword = str(input("Enter the desire keyword (): "))
generated_keywords = generate_keywords_by_rating(selected_rating, num_keywords_to_generate)
for keyword in generated_keywords:
    print(keyword)

Enter the desired rating (1-4): 1
Enter the desire keyword (): Bais Alert
Lack of Listening
Chaotically Disorganized
Limited Knowledge
Micro Mania
Questionable Ethics
Hasty Execution
Discouraging Attitude
Lack of Passion
Unsatisfying Support
Disengaging Vibes